### ISSUE TITLE
Missing dependencies in deploy.sh fase

### ISSUE THREAD

**Issue by amon-ra** [glic3rinu/django-orchestra#11]
Script deploy.sh fails to install some dependencies.

If I first install:
- zlib1g-dev
- libcrack2-dev
- postgresql
- python3-crypto
- rabbitmq-server

and pip lib:
- amqp
- anyjson

Deploys ok

**Comment by glic3rinu** [comment]
thanks for reporting, 
I believe should be fixed now.
